language: php

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COVERAGE=0

matrix:
  include:
    - php: 7.1
      env: COVERAGE=1 LARAVEL='5.7.*' TESTBENCH='3.7.*'
    - php: 7.1
      env: COVERAGE=1 LARAVEL='5.8.*' TESTBENCH='3.8.*'
    - php: 7.2
      env: COVERAGE=1 LARAVEL='5.7.*' TESTBENCH='3.7.*'
    - php: 7.2
      env: COVERAGE=1 LARAVEL='5.8.*' TESTBENCH='3.8.*'
    - php: 7.2
      env: COVERAGE=1 LARAVEL='6.*' TESTBENCH='4.*'
    - php: 7.2
      env: COVERAGE=1 LARAVEL='7.*' TESTBENCH='5.*'
    - php: 7.3
      env: COVERAGE=1 LARAVEL='5.7.*' TESTBENCH='3.7.*'
    - php: 7.3
      env: COVERAGE=1 LARAVEL='5.8.*' TESTBENCH='3.8.*'
    - php: 7.3
      env: COVERAGE=1 LARAVEL='6.*' TESTBENCH='4.*'
    - php: 7.3
      env: COVERAGE=1 LARAVEL='7.*' TESTBENCH='5.*'
  fast_finish: true

before_install:
  - cp phpunit.xml.dist phpunit.xml
  - travis_retry composer require "laravel/framework:${LARAVEL}" --no-interaction --no-update
  - travis_retry composer require --dev "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - composer test:ci

after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi