language: php

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: hhvm-3.18
      sudo: required
      dist: trusty
      env: LARAVEL='5.4.*' TESTBENCH='3.4.*'
      group: edge
    - php: 7.1
      env: LARAVEL='5.4.*' TESTBENCH='3.4.*'
    - php: 7.1
      env: LARAVEL='5.5.*' TESTBENCH='3.5.*'
    - php: 7.1
      env: LARAVEL='5.6.*' TESTBENCH='3.6.*'
    - php: 7.1
      env: LARAVEL='5.7.*' TESTBENCH='3.7.*'
    - php: 7.1
      env: LARAVEL='5.8.*' TESTBENCH='3.8.*'
    - php: 7.2
      env: LARAVEL='5.4.*' TESTBENCH='3.4.*'
    - php: 7.2
      env: LARAVEL='5.5.*' TESTBENCH='3.5.*'
    - php: 7.2
      env: LARAVEL='5.6.*' TESTBENCH='3.6.*'
    - php: 7.2
      env: LARAVEL='5.7.*' TESTBENCH='3.7.*'
    - php: 7.2
      env: LARAVEL='5.8.*' TESTBENCH='3.8.*'
    - php: 7.2
      env: LARAVEL='6.*' TESTBENCH='4.*'
    - php: 7.2
      env: LARAVEL='7.*' TESTBENCH='5.*'
    - php: 7.3
      env: LARAVEL='5.4.*' TESTBENCH='3.4.*'
    - php: 7.3
      env: LARAVEL='5.5.*' TESTBENCH='3.5.*'
    - php: 7.3
      env: LARAVEL='5.6.*' TESTBENCH='3.6.*'
    - php: 7.3
      env: LARAVEL='5.7.*' TESTBENCH='3.7.*'
    - php: 7.3
      env: LARAVEL='5.8.*' TESTBENCH='3.8.*'
    - php: 7.3
      env: LARAVEL='6.*' TESTBENCH='4.*'
    - php: 7.3
      env: LARAVEL='7.*' TESTBENCH='5.*'
  fast_finish: true

before_install:
  - travis_retry composer self-update
  - travis_retry composer require "illuminate/contracts:${LARAVEL}" --no-interaction --no-update
  - travis_retry composer require-dev "orchestra/testbench:${LARAVEL}" --no-interaction --no-update

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - composer test:ci